### ISSUE TITLE
Reduce API surface area

### ISSUE THREAD

**Issue by vallahaye** [vallahaye/go-batcher#4]
For the moment, calling [Batcher.Run](https://pkg.go.dev/go.vallahaye.net/batcher#Batcher.Run) starts the batching process in a separate Goroutine managed by Go Batcher, considering that the calling site should not be blocked.

This assumption leads to a larger API surface area, which has nothing to do with batching, and a more complex implementation due to its asynchronous nature.

We should therefore replace the current startup mechanism with a synchronous implementation and leave it up to developers to choose how it should be integrated into their call sites.

For example, a call to `Run` could be replaced by the following:

```go
ctx, cancel := context.WithCancel(context.Background())
defer cancel()

go func() {
  b.Batch(ctx)
}()
```

**Tasks:**

- [ ] Remove methods `Batcher.Run` and `Batcher.Shutdown`
- [ ] Add a new method `Batcher.Batch`, running the batching process in a blocking fashion
- [ ] Update unit tests accordingly
- [ ] Update the README's example
