### ISSUE TITLE
Eliminate the notion of "adding" in favor of "sending"

### ISSUE THREAD

**Issue by vallahaye** [vallahaye/go-batcher#7]
Asserting that batchers receive operations implies that these operations were **sent** in the first place. Therefore, we should revamp the API and the documentation around this semantics.

**Tasks:**

- [x] Rename the `Batcher.Add` method to `Batcher.Send`
- [x] Update unit tests accordingly
- [x] Update the documentation accordingly
